# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json

# Import API key
from api_keys import g_key
gmaps.configure(api_key=g_key)

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
# Read csv, store it as dataframe, and display df head
cities_df = pd.read_csv("Resources/city_weather_data.csv")
cities_df.head()

,Unnamed: 0,City,Latitude,Longitude,Max. Temp (F),Humidity (%),Cloudiness (%),Wind Speed (MPH),Country,Date
0,0,rikitea,-23.1203,-134.9692,73.54,74,36,17.83,PF,1627323638
1,1,norman wells,65.2820,-126.8329,60.84,63,75,11.50,CA,1627323638
2,2,atuona,-9.8000,-139.0333,77.52,70,55,25.08,PF,1627323638
3,3,pitkyaranta,61.5734,31.4792,63.52,81,55,3.31,RU,1627323639
4,4,mataura,-46.1927,168.8643,42.48,98,91,2.95,NZ,1627323114

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
# Create heatmap
fig = gmaps.figure()

# Assign values for location and humidity, which will be used at location and
# weight
locations = cities_df[["Latitude", "Longitude"]]
humidity = cities_df["Humidity (%)"]

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=10,
                                 point_radius=1)

# Add heat layer
fig.add_layer(heat_layer)

# Display heatmap
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [4]:
# I will be using the following weather criteria:
# Temperature below 90 F, above 60 F
# Humidity below 60%
# Wind speed below 5 mph

# Create filtered df using loc
filtered_cities_df = cities_df.loc[(cities_df["Max. Temp (F)"] <= 90) &
                                  (cities_df["Max. Temp (F)"] >= 60) &
                                  (cities_df["Humidity (%)"] <= 60) &
                                  (cities_df["Wind Speed (MPH)"] <= 5)]

filtered_cities_df = filtered_cities_df.reset_index()

# Display df
filtered_cities_df

,index,Unnamed: 0,City,Latitude,Longitude,Max. Temp (F),Humidity (%),Cloudiness (%),Wind Speed (MPH),Country,Date
0,12,12,albany,42.6001,-73.9662,86.58,51,1,4.00,US,1627323443
1,34,34,bethel,41.3712,-73.4140,89.08,56,1,1.99,US,1627323647
2,46,46,narsaq,60.9167,-46.0500,66.42,50,44,3.56,GL,1627323651
3,69,69,mosquera,4.7059,-74.2302,68.09,49,40,3.44,CO,1627323658
4,100,100,thompson,55.7435,-97.8558,66.36,32,20,3.44,CA,1627323667
5,103,103,suntar,62.1444,117.6319,68.29,59,15,3.62,RU,1627323669
6,107,107,teya,60.3778,92.6267,72.46,57,58,3.44,RU,1627323670
7,164,164,alvaraes,-3.2208,-64.8042,89.47,44,91,3.85,BR,1627323687
8,165,165,northampton,40.8754,-75.2499,88.84,40,97,1.01,US,1627323687
9,190,190,nevsehir,38.9167,34.6667,76.21,29,20,4.61,TR,1627323695
10,191,191,hay river,60.8156,-115.7999,71.58,53,20,1.14,CA,1627323421
11,219,219,keuruu,62.2667,24.7000,78.98,40,28,3.98,FI,1627323703
12,243,243,velizh,55.6056,31.1967,70.84,56,43,3.60,RU,1627323710
13,247,247,murmino,54.6036,40.0544,65.19,58,56,4.65,RU,1627323711
14,254,254,demba,-5.5100,22.2667,75.51,28,84,2.93,CD,1627323713
15,277,277,saint george,37.1041,-113.5841,89.80,49,1,3.00,US,1627323662
16,363,363,chanika,-5.4167,38.0167,62.89,56,61,3.42,TZ,1627323747
17,365,365,venustiano carranza,19.4300,-99.0992,73.15,42,20,1.99,MX,1627323748
18,385,385,orzinuovi,45.4040,9.9216,82.45,52,68,1.99,IT,1627323754
19,390,390,ozimek,50.6794,18.2137,81.95,59,41,1.99,PL,1627323755
20,443,443,port alberni,49.2413,-124.8028,77.16,44,1,2.15,CA,1627323774
21,445,445,aksu,41.1231,80.2644,89.40,19,0,4.41,CN,1627323775
22,456,456,boende,-0.2167,20.8667,85.06,32,87,2.57,CD,1627323779
23,474,474,tyulgan,52.3405,56.1660,62.19,41,49,3.22,RU,1627323785
24,481,481,broome,42.2506,-75.8330,85.69,48,40,4.00,US,1627323788
25,486,486,marfino,55.7028,37.3822,75.45,52,0,2.24,RU,1627323790
26,494,494,kavos,38.8268,22.8322,83.14,58,0,3.67,GR,1627323792
27,508,508,ryazan,54.6197,39.7400,65.34,58,55,4.05,RU,1627323793
28,542,542,kosel,50.3356,18.1433,82.08,54,47,1.86,PL,1627323809
29,553,553,katakwi,1.8911,33.9661,71.15,58,100,3.51,UG,1627323813

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [5]:
# Setup hotel_df, with columns for hotel name, lat, lng, and city
# Initialize 'city' column with cities from filtered_cities_df
hotel_df = pd.DataFrame(columns=["Hotel Name", "Latitude", "Longitude", "City", "Country"])
hotel_df["City"] = filtered_cities_df["City"]
hotel_df["Country"] = filtered_cities_df["Country"]
hotel_df = hotel_df.reset_index()

# Setup for query
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
params = {
    "location": "",
    "rankyby": "distance",
    "type": "hotel",
    "keyword": "hotel",
    "radius": 5000,
    "key": g_key
}


# Loops through hotel_df and finds closest hotel to city's listed coordinates
for index, row in hotel_df.iterrows():
    # Gets city coordinates from filtered_city_df
    lat = float(filtered_cities_df.loc[filtered_cities_df["City"] == row.City,"Latitude"])
    lng = float(filtered_cities_df.loc[filtered_cities_df["City"] == row.City, "Longitude"])

    # Sets city coordinates in paramters
    params["location"] = f"{lat}, {lng}"

    # Gets query and converts it to json
    get_hotel = requests.get(base_url, params=params).json()
    
    # Finds latitude, longitude, and hotel name and appends it to dataframe
    try:
        print(f"Finding closest hotel in {row.City}")
        
        hotel_df.loc[index, "Latitude"] = get_hotel["results"][1]["geometry"]["location"]["lat"]
        hotel_df.loc[index, "Longitude"] = get_hotel["results"][1]["geometry"]["location"]["lng"]
        hotel_df.loc[index, "Hotel Name"] = get_hotel["results"][1]["name"]
        
        
    # If this information is not found, or there is an error, returns the following
    except:
        print("Cannot find hotel in this city.")

# Display df
hotel_df

Finding closest hotel in albany
Cannot find hotel in this city.
Finding closest hotel in bethel
Finding closest hotel in narsaq
Finding closest hotel in mosquera
Finding closest hotel in thompson
Finding closest hotel in suntar
Finding closest hotel in teya
Cannot find hotel in this city.
Finding closest hotel in alvaraes
Cannot find hotel in this city.
Finding closest hotel in northampton
Cannot find hotel in this city.
Finding closest hotel in nevsehir
Cannot find hotel in this city.
Finding closest hotel in hay river
Finding closest hotel in keuruu
Finding closest hotel in velizh
Finding closest hotel in murmino
Cannot find hotel in this city.
Finding closest hotel in demba
Cannot find hotel in this city.
Finding closest hotel in saint george
Finding closest hotel in chanika
Finding closest hotel in venustiano carranza
Finding closest hotel in orzinuovi
Cannot find hotel in this city.
Finding closest hotel in ozimek
Finding closest hotel in port alberni
Finding closest hotel in aksu
Finding closest hotel in boende
Cannot find hotel in this city.
Finding closest hotel in tyulgan
Finding closest hotel in broome
Cannot find hotel in this city.
Finding closest hotel in marfino
Finding closest hotel in kavos
Cannot find hotel in this city.
Finding closest hotel in ryazan
Finding closest hotel in kosel
Cannot find hotel in this city.
Finding closest hotel in katakwi

,index,Hotel Name,Latitude,Longitude,City,Country
0,0,NaN,NaN,NaN,albany,US
1,1,Best Western Danbury/Bethel,41.416134,-73.400703,bethel,US
2,2,Narsaq Kayak Hostel,60.913382,-46.050511,narsaq,GL
3,3,Hotel Funza Real,4.714478,-74.215013,mosquera,CO
4,4,Burntwood Hotel,55.744729,-97.858732,thompson,CA
5,5,Дом у Мамы,62.156307,117.612774,suntar,RU
6,6,NaN,NaN,NaN,teya,RU
7,7,NaN,NaN,NaN,alvaraes,BR
8,8,NaN,NaN,NaN,northampton,US
9,9,NaN,NaN,NaN,nevsehir,TR
10,10,Castaways Cottages,60.849462,-115.838794,hay river,CA
11,11,Huoneistohotelli Pappilanpuisto,62.253038,24.705069,keuruu,FI
12,12,Sberbank,55.605839,31.193049,velizh,RU
13,13,NaN,NaN,NaN,murmino,RU
14,14,NaN,NaN,NaN,demba,CD
15,15,Quality Inn,37.127359,-113.525174,saint george,US
16,16,P.T Stone Park Hotel,-5.422404,38.02569,chanika,TZ
17,17,Hilton Mexico City Airport,19.435919,-99.081685,venustiano carranza,MX
18,18,NaN,NaN,NaN,orzinuovi,IT
19,19,Bajka Restauracja Hotel,50.695447,18.28609,ozimek,PL
20,20,Swept Away Inn,49.235388,-124.816475,port alberni,CA
21,21,Jianshe Hotel,41.161712,80.281689,aksu,CN
22,22,NaN,NaN,NaN,boende,CD
23,23,Komfort,52.342891,56.162308,tyulgan,RU
24,24,NaN,NaN,NaN,broome,US
25,25,Pogosti.ru,55.720325,37.463302,marfino,RU
26,26,NaN,NaN,NaN,kavos,GR
27,27,Amaks Congress Hotel,54.629474,39.720039,ryazan,RU
28,28,NaN,NaN,NaN,kosel,PL
29,29,Eden Guest House,1.918181,33.952975,katakwi,UG

In [6]:
display(hotel_df)

,index,Hotel Name,Latitude,Longitude,City,Country
0,0,NaN,NaN,NaN,albany,US
1,1,Best Western Danbury/Bethel,41.416134,-73.400703,bethel,US
2,2,Narsaq Kayak Hostel,60.913382,-46.050511,narsaq,GL
3,3,Hotel Funza Real,4.714478,-74.215013,mosquera,CO
4,4,Burntwood Hotel,55.744729,-97.858732,thompson,CA
5,5,Дом у Мамы,62.156307,117.612774,suntar,RU
6,6,NaN,NaN,NaN,teya,RU
7,7,NaN,NaN,NaN,alvaraes,BR
8,8,NaN,NaN,NaN,northampton,US
9,9,NaN,NaN,NaN,nevsehir,TR
10,10,Castaways Cottages,60.849462,-115.838794,hay river,CA
11,11,Huoneistohotelli Pappilanpuisto,62.253038,24.705069,keuruu,FI
12,12,Sberbank,55.605839,31.193049,velizh,RU
13,13,NaN,NaN,NaN,murmino,RU
14,14,NaN,NaN,NaN,demba,CD
15,15,Quality Inn,37.127359,-113.525174,saint george,US
16,16,P.T Stone Park Hotel,-5.422404,38.02569,chanika,TZ
17,17,Hilton Mexico City Airport,19.435919,-99.081685,venustiano carranza,MX
18,18,NaN,NaN,NaN,orzinuovi,IT
19,19,Bajka Restauracja Hotel,50.695447,18.28609,ozimek,PL
20,20,Swept Away Inn,49.235388,-124.816475,port alberni,CA
21,21,Jianshe Hotel,41.161712,80.281689,aksu,CN
22,22,NaN,NaN,NaN,boende,CD
23,23,Komfort,52.342891,56.162308,tyulgan,RU
24,24,NaN,NaN,NaN,broome,US
25,25,Pogosti.ru,55.720325,37.463302,marfino,RU
26,26,NaN,NaN,NaN,kavos,GR
27,27,Amaks Congress Hotel,54.629474,39.720039,ryazan,RU
28,28,NaN,NaN,NaN,kosel,PL
29,29,Eden Guest House,1.918181,33.952975,katakwi,UG

In [7]:
# Cleanup of df - drop rows where a hotel cannot be found and resets index
hotel_df = hotel_df.dropna(axis=0)
hotel_df

,index,Hotel Name,Latitude,Longitude,City,Country
1,1,Best Western Danbury/Bethel,41.416134,-73.400703,bethel,US
2,2,Narsaq Kayak Hostel,60.913382,-46.050511,narsaq,GL
3,3,Hotel Funza Real,4.714478,-74.215013,mosquera,CO
4,4,Burntwood Hotel,55.744729,-97.858732,thompson,CA
5,5,Дом у Мамы,62.156307,117.612774,suntar,RU
10,10,Castaways Cottages,60.849462,-115.838794,hay river,CA
11,11,Huoneistohotelli Pappilanpuisto,62.253038,24.705069,keuruu,FI
12,12,Sberbank,55.605839,31.193049,velizh,RU
15,15,Quality Inn,37.127359,-113.525174,saint george,US
16,16,P.T Stone Park Hotel,-5.422404,38.02569,chanika,TZ
17,17,Hilton Mexico City Airport,19.435919,-99.081685,venustiano carranza,MX
19,19,Bajka Restauracja Hotel,50.695447,18.28609,ozimek,PL
20,20,Swept Away Inn,49.235388,-124.816475,port alberni,CA
21,21,Jianshe Hotel,41.161712,80.281689,aksu,CN
23,23,Komfort,52.342891,56.162308,tyulgan,RU
25,25,Pogosti.ru,55.720325,37.463302,marfino,RU
27,27,Amaks Congress Hotel,54.629474,39.720039,ryazan,RU
29,29,Eden Guest House,1.918181,33.952975,katakwi,UG

In [8]:
hotel_df

,index,Hotel Name,Latitude,Longitude,City,Country
1,1,Best Western Danbury/Bethel,41.416134,-73.400703,bethel,US
2,2,Narsaq Kayak Hostel,60.913382,-46.050511,narsaq,GL
3,3,Hotel Funza Real,4.714478,-74.215013,mosquera,CO
4,4,Burntwood Hotel,55.744729,-97.858732,thompson,CA
5,5,Дом у Мамы,62.156307,117.612774,suntar,RU
10,10,Castaways Cottages,60.849462,-115.838794,hay river,CA
11,11,Huoneistohotelli Pappilanpuisto,62.253038,24.705069,keuruu,FI
12,12,Sberbank,55.605839,31.193049,velizh,RU
15,15,Quality Inn,37.127359,-113.525174,saint george,US
16,16,P.T Stone Park Hotel,-5.422404,38.02569,chanika,TZ
17,17,Hilton Mexico City Airport,19.435919,-99.081685,venustiano carranza,MX
19,19,Bajka Restauracja Hotel,50.695447,18.28609,ozimek,PL
20,20,Swept Away Inn,49.235388,-124.816475,port alberni,CA
21,21,Jianshe Hotel,41.161712,80.281689,aksu,CN
23,23,Komfort,52.342891,56.162308,tyulgan,RU
25,25,Pogosti.ru,55.720325,37.463302,marfino,RU
27,27,Amaks Congress Hotel,54.629474,39.720039,ryazan,RU
29,29,Eden Guest House,1.918181,33.952975,katakwi,UG

In [9]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap

info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""

# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Latitude", "Longitude"]]

In [11]:
# Add marker layer ontop of heat map
vacation_layer = gmaps.symbol_layer(locations, fill_color="red", stroke_color="red", scale=5)
marker_layer = gmaps.symbol_layer(locations, info_box_content=hotel_info)
fig.add_layer(vacation_layer)
fig.add_layer(marker_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))